-- Generated by nwg-displays on 2026-06-12 at 22:51:31. Do not edit manually.

hl.monitor({
    output = "desc:BOE 0x09CA",
    mode = "1920x1080@60.0",
    position = "798x385",
    scale = 1.0
})
hl.monitor({
    output = "desc:Dell Inc. DELL P2725H D4WXM14",
    mode = "1920x1080@60.0",
    position = "2718x385",
    scale = 1.0
})
