#!/bin/bash

# Exit if a command exits with non-zero status

set -e

echo "Starting system upgrade & cleanup..."

# Clean leftover temp download files
sudo rm -rf /var/cache/pacman/pkg/download-*

echo "Upgrading system packages..."
yay -Syu --noconfirm 

# Clear pacman cache
echo "Cleaning old pacman cached packages..."
sudo paccache -rk1
sudo paccache -ruk0

# Remove orphaned pacman packages
echo "Removing orphaned pacman packages..."
orphans=$(pacman -Qdtq)
if [ -n "$orphans" ]; then
	sudo pacman -Rns --noconfirm $orphans
else
	echo "No orphaned packages found."
fi

# Clean up systemd journal logs (older than 2 weeks)
echo "Cleaning up systemd journal logs..."
sudo journalctl --vacuum-time=2weeks

# Clean up user cache
echo "Cleaning user cache..."
rm -rf ~/.cache/*
rm -rf ~/.local/share/Trash/*

